### ISSUE TITLE
quboo web client has default localhost:8080 config

### ISSUE THREAD

**Issue by anantmnavagale** [mechero/code-quality-game#14]
While creating team I encounter error. When toy click on "Save", it by default calls "localhost:8080".
But I am accessing the app from another machine

**Comment by mechero** [comment]
Thanks, this is a bug indeed. I extracted that a configuration parameter but I guess that at some point I missed that change. 
I will take care of this soon.

**Comment by mechero** [comment]
@anantmnavagale, now the app allows you to define where the Quboo backend service is located (v1.0.2). Let me know your feedback.
