### ISSUE TITLE
Authentication against sonarqube fails

### ISSUE THREAD

**Issue by mimitecan** [mechero/code-quality-game#16]
Hi,

I am trying to user your wonderful code game. I installed a local sonar qube 7.5 on a Win2016 Server. The docker container is up and running inside the server as well. Whenever quboo backend starts retrieving the users from sonar with http://localhost:9000/api/users/search?p=1&ps=500 I get a 401 back. I have inserted the API key, answer is always the same as I get when I try to call the API without authentication (401). The API key itself seems to be working, using it with postman gives me the list of users back.

quboo-backend_1     | 2019-01-11 14:08:43.127 TRACE 1 --- [pool-1-thread-1] c.t.d.m.u.service.SonarUsersRetriever    : Retrieving users, page 1
quboo-backend_1     | 2019-01-11 14:08:43.192 TRACE 1 --- [pool-1-thread-1] c.t.d.m.u.service.SonarUsersRetriever    : URI: http://localhost:9000/api/users/search?p=1&ps=500
quboo-backend_1     | 2019-01-11 14:08:43.219  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
quboo-backend_1     | 2019-01-11 14:08:43.243  INFO 1 --- [           main] c.t.devgame.Application                  : Started Application in 15.316 seconds (JVM running for 17.436)
quboo-backend_1     | 2019-01-11 14:08:43.431 ERROR 1 --- [pool-1-thread-1] c.t.d.m.u.service.SonarUsersRetriever    : Error while trying to retrieve users from SonarQube, page 1
quboo-backend_1     |
quboo-backend_1     | org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://localhost:9000/api/users/search": Connection refused (Connection refused); nested exception is java.net.ConnectException: Connection refused (Connection refused)

Any idea what I am doing wrong?

Regards,

Miriam

**Comment by mechero** [comment]
Hi Miriam,

I tried connecting with Sonarqube 7.5 using authentication and it worked. At the bottom of this answer are the steps I made, however, looking at the stacktrace, that doesn't seem related to Authorization but to network access. If you pass `localhost` as environment variable, the Quboo Docker container will try to find Sonarqube in its own container, but that's not what you want. 

## In case it's a Connection issue

If you installed Sonarqube in the host and Quboo is running with Docker, what you want is access from the Quboo container to the host. See https://docs.docker.com/docker-for-windows/networking/#known-limitations-use-cases-and-workarounds

**Basically, it should be fine if you're using Docker 18 or above to replace `localhost` by `host.docker.internal`.**

## In case it's the token

1. Create a token in Sonarqube (for an account with access to users and issues)

<img width="642" alt="screenshot 2019-01-12 at 09 58 08" src="https://user-images.githubusercontent.com/2767217/51071468-a18c4f80-1651-11e9-80d4-d62bc061764f.png">

<img width="620" alt="screenshot 2019-01-12 at 09 58 36" src="https://user-images.githubusercontent.com/2767217/51071471-a94bf400-1651-11e9-8a39-ed724f11420a.png">

2. Passed this token as an environment variable to Quboo (e.g. via `.env` file existing in the same folder as the `docker-compose` file). This is the step you might be doing wrong, if the environment variable has a typo or is misconfigured you might get those 401 codes.

```
SONAR_TOKEN=3da17bb876d3599147ad6e9d15cf26afe4318961
```

Let me know if any of these solutions work for you. I'll update the docs for the case you're trying to run.

**Comment by mechero** [comment]
I think what you're seeing now is due to the fact that you didn't add users to teams. Navigate to the Organizer, make sure you can see non-assigned players (by checking the checkbox), create one or more teams and assign players to them. Hope that helps.

**Comment by mimitecan** [comment]
It did indeed! Works like a charm - thank you very much.
