### ISSUE TITLE
Question - Reseting statistics is a bit unclear

### ISSUE THREAD

**Issue by ittaiyam** [mechero/code-quality-game#18]
Hi,

I have setup Quboo in my workplace recently and it looks like a smart and fun solution to addressing our code debt problem.

It is unclear to me though, when resetting statistics, they just come back again. I only guess it is because Quboo recalculates based on the fixed and assigned issues on Sonar.
But suppose we want to reset the score every, let's say, month (we have monthly sprints), so that who came short last month can have a chance to shine. How would we be able to do that?

I thought maybe I can unassign users from fixed issues, but SonarQube (7.6) doesn't allow this.
I thought also whether Quboo can calculate the statistics based on a legacy date (created before a date) and a solution date. (solved after a date)

It is such a wonderful tool and I would very much appreciate a feedback on how to better use it.

Thanks.

**Comment by mechero** [comment]
Hi @ittaiyam,

Thanks for using Quboo, it's actually great having feedback from users. You're right, if you want to keep the Legacy Date the same across multiple iterations of the game, the stats will just come back. In the current version, you would need to move the Legacy Date to prevent this.

To avoid it, I have implemented Campaign functionality so you don't need to delete the stats, simply they will not count for a new Campaign. This functionality is coming with Quboo in its cloud version, that's something I'm finishing at the moment. 

Would you like to participate in the beta? I could give you the ability to create an account and give it a try in about two weeks. No commitments, no subscriptions, just in exchange for some feedback. 😁

**Comment by ittaiyam** [comment]
@mechero 
Sounds good, but I'd rather continue using the standalone version.
Will it be OK to pull request?
I saw SQ issues have a date of resolution. I think I could inject the "campaign start" date to the ScoreCardServiceImpl the same way the legacy date is injected, and use this date to filter issues by their resolution date.

**Comment by mechero** [comment]
Sure, go ahead with the PR. I think it's a good and simple idea. Then, that property can be exposed as configuration like the rest of parameters and I can include it in the docs.
Thanks for contributing!

**Comment by ittaiyam** [comment]
#

**Comment by ittaiyam** [comment]
#19 
Pull request sent.

**Comment by mechero** [comment]
Moved to https://github.com/mechero/code-quality-game/pull/20

**Comment by mechero** [comment]
Docs added to the site on https://github.com/mechero/quboo-web/pull/10

**Comment by mechero** [comment]
Merged
