### ISSUE TITLE
sonar run error

### ISSUE THREAD

**Issue by hendisantika** [mechero/code-quality-game#2]
Nice example,

But I have some issue when running the CLI  :
 
```
mvn sonar:sonar
Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.2:sonar (default-cli) on project code-quality-game: /Users/hendisantika/Documents/IdeaProjects/code-quality-game/sonar-connector doesn't seem to be contained in a Git repository
```
I have run my sonar service.

Do you have any solution?

**Comment by mechero** [comment]
Hi,
By default Sonarqube agent will try to extract information from the git repository. It seems your folder is not a git repo though, so it might be a solution for you to remove this line from `pom.xml`:
`<sonar.scm.provider>git</sonar.scm.provider>`
Give it a try and let me know.
