### ISSUE TITLE
Get issues URL format

### ISSUE THREAD

**Issue by gvasquez-waypoint** [mechero/code-quality-game#3]
Seems like your code might have been developed using a now obsolete (deprecated) API, as I had to replace the pipe characters with ampersands in `es.macero.cqgame.modules.retriever.service.SonarDataRetriever` class:

`private static final String GET_ISSUES_COMMAND = "/api/issues/search?assignees={assignees}&resolutions={resolutions}&p={page}&ps={pageSize}";`

I tried to commit the patch to `master` but seems like it's forbidden, perhaps I just don't know the procedure to do it.

**Comment by mechero** [comment]
Thanks! Finally, they changed it to be compliant with standards. I can fix it, or you can also contribute to the repo by forking it and creating a pull request, [here are the instructions](https://gist.github.com/Chaser324/ce0505fbed06b947d962).

**Comment by mechero** [comment]
After a big update, I fixed this one. Check out the new version, is much better than before 😄
